### ISSUE TITLE
Please add MailJet as name to notes.

### ISSUE THREAD

**Issue by cmsbased** [cmsbased/mailjet#1]
Please add MailJet as name to notes. It is blank at the moment and a bit confusing.

![image](https://user-images.githubusercontent.com/5864393/37391631-2301c6d0-2742-11e8-8bea-d5a4d21e336c.png)

**Comment by RocketSharck** [comment]
we can add MailJet name in to body.

Or we can manually create admin user with name MailJet. And if it exist we can use it for name.

**Comment by cmsbased** [comment]
Body text is fine. It does not have to be overly complex. Minor UI issue. Thanks!
