### ISSUE TITLE
Webhook file access limit.

### ISSUE THREAD

**Issue by cmsbased** [cmsbased/mailjet#4]
Can we lock  `modules/addons/mailjet/web-hook.php` to mailjet server IP?  I think we did this for Github module.

**Comment by RocketSharck** [comment]
I can't find any mentioning about ip limitation for web-hook.

according to api docs we can use basic authentication.

**Comment by cmsbased** [comment]
Please implement the easiest and best option. I just do not want ticket note spam or any other possible 
 problem.

**Comment by cmsbased** [comment]
Can we automatically update URL with AUTH info, so the user can just copy and paste?

![image](https://user-images.githubusercontent.com/5864393/37546113-cceb48f0-2941-11e8-8b14-57f7f9cad730.png)

**Comment by RocketSharck** [comment]
Yes, we can
