### ISSUE TITLE
Better styling for clicked or opened notes.

### ISSUE THREAD

**Issue by cmsbased** [cmsbased/mailjet#6]
When mailjet adds notes they are all red styled like this:

```
#ticketreplies .reply.note {
    border: 1px dashed #f0b6c3;
    background-color: #ffdee5;
    box-shadow: 0 0 5px #ffd9e1;
}
```

Can we use green #c3e8ce on all 3 properties for `clicked` and `opened` and keep existing red for the rest of the statuses?

We will not be able to edit admin template so my guess is JS code via admin area output hook?

**Comment by cmsbased** [comment]
Stopped working completely for support tickets after I deployed latest commit.

**Comment by RocketSharck** [comment]
Please try to deactivate/activate module.

If not help try to enable debug mode. 
Export module logs from db to file
/admin/addonmodules.php?module=mailjet&export_logs=1

**Comment by cmsbased** [comment]
After reset the notes are back however no extra styling - color is applied.

![image](https://user-images.githubusercontent.com/5864393/41683101-aeab9a50-74a7-11e8-91dc-bc118cd55ddb.png)


I did code search and could not find `c3e8ce`

**Comment by RocketSharck** [comment]
Can't replicate.

I wrote it in different way.
